/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#475569",
        "on-error": "#ffffff",
        "gold-primary": "#B48328",
        "surface": "#FAFAEB",
        "primary-container": "#B48328",
        "on-primary-fixed": "#281900",
        "on-primary-container": "#614205",
        "secondary-fixed-dim": "#f2be72",
        "navy-surface": "#F3F3DB",
        "error": "#ffb4ab",
        "surface-dim": "#EAEAC7",
        "primary-fixed": "#ffdeae",
        "surface-container-low": "#F6F6E3",
        "inverse-on-surface": "#f8fafc",
        "tertiary-fixed-dim": "#aac8f6",
        "secondary-fixed": "#ffddb1",
        "on-secondary-fixed-variant": "#624000",
        "surface-container-high": "#EBEBC8",
        "tertiary-fixed": "#d4e3ff",
        "outline": "#9b8f80",
        "on-tertiary": "#0e3157",
        "on-secondary-container": "#e6b369",
        "surface-container-lowest": "#FDFDF5",
        "surface-tint": "#edbf79",
        "on-secondary": "#442b00",
        "on-tertiary-fixed-variant": "#29486f",
        "on-tertiary-fixed": "#001c39",
        "surface-variant": "#F3F3DB",
        "gold-secondary": "#8c6217",
        "secondary-container": "#684400",
        "primary": "#facb84",
        "border-subtle": "rgba(0, 0, 0, 0.1)",
        "secondary": "#f2be72",
        "white-muted": "rgba(30, 41, 59, 0.75)",
        "surface-container-highest": "#E4E4B7",
        "on-primary": "#ffffff",
        "surface-container": "#F1F1D6",
        "inverse-primary": "#7a581c",
        "primary-fixed-dim": "#edbf79",
        "on-tertiary-container": "#2a4970",
        "on-background": "#1E293B",
        "background": "#FAFAEB",
        "surface-bright": "#FFFFF5",
        "navy-bg": "#FAFAEB",
        "tertiary-container": "#9bb9e6",
        "tertiary": "#b9d5ff",
        "error-container": "#93000a",
        "on-surface": "#1E293B",
        "on-primary-fixed-variant": "#604104",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#291800",
        "inverse-surface": "#1E293B",
        "outline-variant": "#4e4539"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full-custom": "0.75rem"
      },
      spacing: {
        "stack-lg": "48px",
        "section-gap": "40px",
        "stack-sm": "16px",
        "stack-md": "32px",
        "margin-main": "24px",
        "gutter-grid": "16px"
      },
      fontFamily: {
        "headline-sm": ["Oswald", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "headline-lg": ["Oswald", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Oswald", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-vertical": ["Oswald", "sans-serif"]
      },
      fontSize: {
        "headline-sm": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg": ["36px", { "lineHeight": "40px", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "display-vertical": ["20px", { "lineHeight": "normal", "letterSpacing": "0.15em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
